sonar.projectKey=tn.esprit:frontend
sonar.projectName=Frontend
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,**/*.spec.ts
sonar.sourceEncoding=UTF-8
sonar.language=js,ts
